// Twelve compositions authored for this application; eleven palette variants per composition.
// Historical IDs are compatibility keys, not names or layout references.
export const REMAINING_DESIGNS = Object.freeze([
  {
    "id": "cvapp-traditional",
    "name": "Editorial Tinta",
    "layout": "single",
    "theme": "editorial",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 39,
    "accent": "#283d52",
    "soft": "#eef2f6",
    "supportsPhoto": false,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 1,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-prime-ats",
    "name": "Archivo Tinta",
    "layout": "sidebar-right",
    "theme": "archive",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 28,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#283d52",
    "soft": "#eef2f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 2,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-pure-ats",
    "name": "Compás Tinta",
    "layout": "single",
    "theme": "compass",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 38,
    "accent": "#283d52",
    "soft": "#eef2f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 3,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-specialist",
    "name": "Prisma Tinta",
    "layout": "sidebar-right",
    "theme": "prism",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 38,
    "rail": 30,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#283d52",
    "soft": "#eef2f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 4,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-simple-ats",
    "name": "Atelier Tinta",
    "layout": "single",
    "theme": "atelier",
    "nameFont": "CV Own Serif",
    "nameSize": 33,
    "margin": 40,
    "accent": "#283d52",
    "soft": "#eef2f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 5,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-corporate",
    "name": "Cronología Tinta",
    "layout": "single",
    "theme": "chronicle",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 37,
    "accent": "#283d52",
    "soft": "#eef2f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 6,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-clear",
    "name": "Umbral Tinta",
    "layout": "sidebar-right",
    "theme": "threshold",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 39,
    "rail": 31,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#283d52",
    "soft": "#eef2f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 7,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-precise-ats",
    "name": "Horizonte Tinta",
    "layout": "single",
    "theme": "horizon",
    "nameFont": "CV Own Sans",
    "nameSize": 31,
    "margin": 38,
    "accent": "#283d52",
    "soft": "#eef2f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 8,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-two-column-ats",
    "name": "Módulo Tinta",
    "layout": "sidebar-right",
    "theme": "module",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 29,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#283d52",
    "soft": "#eef2f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 9,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-balanced",
    "name": "Esencia Tinta",
    "layout": "single",
    "theme": "essence",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 40,
    "accent": "#283d52",
    "soft": "#eef2f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 10,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-header-ats",
    "name": "Cuaderno Tinta",
    "layout": "single",
    "theme": "notebook",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 38,
    "accent": "#283d52",
    "soft": "#eef2f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 11,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-essential",
    "name": "Índice Tinta",
    "layout": "single",
    "theme": "index",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "accent": "#283d52",
    "soft": "#eef2f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 12,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-polished",
    "name": "Editorial Bosque",
    "layout": "single",
    "theme": "editorial",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 39,
    "accent": "#315b4a",
    "soft": "#edf4ef",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 13,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-vivid",
    "name": "Archivo Bosque",
    "layout": "sidebar-right",
    "theme": "archive",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 28,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#315b4a",
    "soft": "#edf4ef",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 14,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-harmonious",
    "name": "Compás Bosque",
    "layout": "single",
    "theme": "compass",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 38,
    "accent": "#315b4a",
    "soft": "#edf4ef",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 15,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-defined",
    "name": "Prisma Bosque",
    "layout": "sidebar-right",
    "theme": "prism",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 38,
    "rail": 30,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#315b4a",
    "soft": "#edf4ef",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 16,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-minimalist",
    "name": "Atelier Bosque",
    "layout": "single",
    "theme": "atelier",
    "nameFont": "CV Own Serif",
    "nameSize": 33,
    "margin": 40,
    "accent": "#315b4a",
    "soft": "#edf4ef",
    "supportsPhoto": false,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 17,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-elegant",
    "name": "Cronología Bosque",
    "layout": "single",
    "theme": "chronicle",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 37,
    "accent": "#315b4a",
    "soft": "#edf4ef",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 18,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-striking",
    "name": "Umbral Bosque",
    "layout": "sidebar-right",
    "theme": "threshold",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 39,
    "rail": 31,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#315b4a",
    "soft": "#edf4ef",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 19,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-nuanced",
    "name": "Horizonte Bosque",
    "layout": "single",
    "theme": "horizon",
    "nameFont": "CV Own Sans",
    "nameSize": 31,
    "margin": 38,
    "accent": "#315b4a",
    "soft": "#edf4ef",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 20,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-executive",
    "name": "Módulo Bosque",
    "layout": "sidebar-right",
    "theme": "module",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 29,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#315b4a",
    "soft": "#edf4ef",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 21,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-character",
    "name": "Esencia Bosque",
    "layout": "single",
    "theme": "essence",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 40,
    "accent": "#315b4a",
    "soft": "#edf4ef",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 22,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-modern",
    "name": "Cuaderno Bosque",
    "layout": "single",
    "theme": "notebook",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 38,
    "accent": "#315b4a",
    "soft": "#edf4ef",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 23,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-creative",
    "name": "Índice Bosque",
    "layout": "single",
    "theme": "index",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "accent": "#315b4a",
    "soft": "#edf4ef",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 24,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-pastel",
    "name": "Editorial Cobre",
    "layout": "single",
    "theme": "editorial",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 39,
    "accent": "#815a42",
    "soft": "#f6f0eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 25,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-visionary",
    "name": "Archivo Cobre",
    "layout": "sidebar-right",
    "theme": "archive",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 28,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#815a42",
    "soft": "#f6f0eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 26,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-confetti",
    "name": "Compás Cobre",
    "layout": "single",
    "theme": "compass",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 38,
    "accent": "#815a42",
    "soft": "#f6f0eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 27,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-entry-level",
    "name": "Prisma Cobre",
    "layout": "sidebar-right",
    "theme": "prism",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 38,
    "rail": 30,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#815a42",
    "soft": "#f6f0eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 28,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-academic",
    "name": "Atelier Cobre",
    "layout": "single",
    "theme": "atelier",
    "nameFont": "CV Own Serif",
    "nameSize": 33,
    "margin": 40,
    "accent": "#815a42",
    "soft": "#f6f0eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 29,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-rirekisho",
    "name": "Cronología Cobre",
    "layout": "single",
    "theme": "chronicle",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 37,
    "accent": "#815a42",
    "soft": "#f6f0eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 30,
    "collection": "owned-20261003"
  },
  {
    "id": "cvapp-shokumukeirekisho",
    "name": "Umbral Cobre",
    "layout": "sidebar-right",
    "theme": "threshold",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 39,
    "rail": 31,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#815a42",
    "soft": "#f6f0eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 31,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-classic-one-column-design-professionals",
    "name": "Horizonte Cobre",
    "layout": "single",
    "theme": "horizon",
    "nameFont": "CV Own Sans",
    "nameSize": 31,
    "margin": 38,
    "accent": "#815a42",
    "soft": "#f6f0eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 32,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-steady-form",
    "name": "Módulo Cobre",
    "layout": "sidebar-right",
    "theme": "module",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 29,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#815a42",
    "soft": "#f6f0eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 33,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-classic-multi-column-serif-black-white",
    "name": "Esencia Cobre",
    "layout": "single",
    "theme": "essence",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 40,
    "accent": "#815a42",
    "soft": "#f6f0eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 34,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-dark-leaves-multi-column-border-left",
    "name": "Cuaderno Cobre",
    "layout": "single",
    "theme": "notebook",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 38,
    "accent": "#815a42",
    "soft": "#f6f0eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 35,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-executive-serif-black-white",
    "name": "Índice Cobre",
    "layout": "single",
    "theme": "index",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "accent": "#815a42",
    "soft": "#f6f0eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 36,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-classic-clear",
    "name": "Editorial Pizarra",
    "layout": "single",
    "theme": "editorial",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 39,
    "accent": "#475569",
    "soft": "#f0f3f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 37,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-true-blue",
    "name": "Archivo Pizarra",
    "layout": "sidebar-right",
    "theme": "archive",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 28,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#475569",
    "soft": "#f0f3f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 38,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-editorial-rule",
    "name": "Compás Pizarra",
    "layout": "single",
    "theme": "compass",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 38,
    "accent": "#475569",
    "soft": "#f0f3f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 39,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-precision-line",
    "name": "Prisma Pizarra",
    "layout": "sidebar-right",
    "theme": "prism",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 38,
    "rail": 30,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#475569",
    "soft": "#f0f3f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 40,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-refined",
    "name": "Atelier Pizarra",
    "layout": "single",
    "theme": "atelier",
    "nameFont": "CV Own Serif",
    "nameSize": 33,
    "margin": 40,
    "accent": "#475569",
    "soft": "#f0f3f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 41,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-silver-banner",
    "name": "Cronología Pizarra",
    "layout": "single",
    "theme": "chronicle",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 37,
    "accent": "#475569",
    "soft": "#f0f3f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 42,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-condensed-rule",
    "name": "Umbral Pizarra",
    "layout": "sidebar-right",
    "theme": "threshold",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 39,
    "rail": 31,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#475569",
    "soft": "#f0f3f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 43,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-classic-portrait",
    "name": "Horizonte Pizarra",
    "layout": "single",
    "theme": "horizon",
    "nameFont": "CV Own Sans",
    "nameSize": 31,
    "margin": 38,
    "accent": "#475569",
    "soft": "#f0f3f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 44,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-corporate-resume-template",
    "name": "Módulo Pizarra",
    "layout": "sidebar-right",
    "theme": "module",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 29,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#475569",
    "soft": "#f0f3f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 45,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-classic-pure",
    "name": "Esencia Pizarra",
    "layout": "single",
    "theme": "essence",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 40,
    "accent": "#475569",
    "soft": "#f0f3f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 46,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-neutral-gray",
    "name": "Cuaderno Pizarra",
    "layout": "single",
    "theme": "notebook",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 38,
    "accent": "#475569",
    "soft": "#f0f3f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 47,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-even-line",
    "name": "Índice Pizarra",
    "layout": "single",
    "theme": "index",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "accent": "#475569",
    "soft": "#f0f3f6",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 48,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-split-rule",
    "name": "Editorial Ciruela",
    "layout": "single",
    "theme": "editorial",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 39,
    "accent": "#6c475d",
    "soft": "#f5eef3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 49,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-mono-underline",
    "name": "Archivo Ciruela",
    "layout": "sidebar-right",
    "theme": "archive",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 28,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#6c475d",
    "soft": "#f5eef3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 50,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-classic-slate",
    "name": "Compás Ciruela",
    "layout": "single",
    "theme": "compass",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 38,
    "accent": "#6c475d",
    "soft": "#f5eef3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 51,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-pure-baseline",
    "name": "Prisma Ciruela",
    "layout": "sidebar-right",
    "theme": "prism",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 38,
    "rail": 30,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#6c475d",
    "soft": "#f5eef3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 52,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-classic-sans",
    "name": "Atelier Ciruela",
    "layout": "single",
    "theme": "atelier",
    "nameFont": "CV Own Serif",
    "nameSize": 33,
    "margin": 40,
    "accent": "#6c475d",
    "soft": "#f5eef3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 53,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-compact-serif",
    "name": "Cronología Ciruela",
    "layout": "single",
    "theme": "chronicle",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 37,
    "accent": "#6c475d",
    "soft": "#f5eef3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 54,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-fine-line",
    "name": "Umbral Ciruela",
    "layout": "sidebar-right",
    "theme": "threshold",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 39,
    "rail": 31,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#6c475d",
    "soft": "#f5eef3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 55,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-clean-slate",
    "name": "Horizonte Ciruela",
    "layout": "single",
    "theme": "horizon",
    "nameFont": "CV Own Sans",
    "nameSize": 31,
    "margin": 38,
    "accent": "#6c475d",
    "soft": "#f5eef3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 56,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-clear-banner",
    "name": "Módulo Ciruela",
    "layout": "sidebar-right",
    "theme": "module",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 29,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#6c475d",
    "soft": "#f5eef3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 57,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-open-form",
    "name": "Esencia Ciruela",
    "layout": "single",
    "theme": "essence",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 40,
    "accent": "#6c475d",
    "soft": "#f5eef3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 58,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-sage-line",
    "name": "Cuaderno Ciruela",
    "layout": "single",
    "theme": "notebook",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 38,
    "accent": "#6c475d",
    "soft": "#f5eef3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 59,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-quiet-focus",
    "name": "Índice Ciruela",
    "layout": "single",
    "theme": "index",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "accent": "#6c475d",
    "soft": "#f5eef3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 60,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-compact-sans",
    "name": "Editorial Azul",
    "layout": "single",
    "theme": "editorial",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 39,
    "accent": "#305e79",
    "soft": "#edf3f8",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 61,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-classic-ledger",
    "name": "Archivo Azul",
    "layout": "sidebar-right",
    "theme": "archive",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 28,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#305e79",
    "soft": "#edf3f8",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 62,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-simple-blush-multi-column-border",
    "name": "Compás Azul",
    "layout": "single",
    "theme": "compass",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 38,
    "accent": "#305e79",
    "soft": "#edf3f8",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 63,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-quiet-blue",
    "name": "Prisma Azul",
    "layout": "sidebar-right",
    "theme": "prism",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 38,
    "rail": 30,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#305e79",
    "soft": "#edf3f8",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 64,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-corporate-panel",
    "name": "Atelier Azul",
    "layout": "single",
    "theme": "atelier",
    "nameFont": "CV Own Serif",
    "nameSize": 33,
    "margin": 40,
    "accent": "#305e79",
    "soft": "#edf3f8",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 65,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-saffron-line",
    "name": "Cronología Azul",
    "layout": "single",
    "theme": "chronicle",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 37,
    "accent": "#305e79",
    "soft": "#edf3f8",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 66,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-professional-multi-column-business-experts",
    "name": "Umbral Azul",
    "layout": "sidebar-right",
    "theme": "threshold",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 39,
    "rail": 31,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#305e79",
    "soft": "#edf3f8",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 67,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-quicksilver-resume-template",
    "name": "Horizonte Azul",
    "layout": "single",
    "theme": "horizon",
    "nameFont": "CV Own Sans",
    "nameSize": 31,
    "margin": 38,
    "accent": "#305e79",
    "soft": "#edf3f8",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 68,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-cobalt-edge",
    "name": "Módulo Azul",
    "layout": "sidebar-right",
    "theme": "module",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 29,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#305e79",
    "soft": "#edf3f8",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 69,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-atlantic-horizon",
    "name": "Esencia Azul",
    "layout": "single",
    "theme": "essence",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 40,
    "accent": "#305e79",
    "soft": "#edf3f8",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 70,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-obsidian-edge",
    "name": "Cuaderno Azul",
    "layout": "single",
    "theme": "notebook",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 38,
    "accent": "#305e79",
    "soft": "#edf3f8",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 71,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-neon-qr-code-multi-column-border",
    "name": "Índice Azul",
    "layout": "single",
    "theme": "index",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "accent": "#305e79",
    "soft": "#edf3f8",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 72,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-hunter-green-multi-column-professional",
    "name": "Editorial Arena",
    "layout": "single",
    "theme": "editorial",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 39,
    "accent": "#766247",
    "soft": "#f6f2eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 73,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-atlantic-standard",
    "name": "Archivo Arena",
    "layout": "sidebar-right",
    "theme": "archive",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 28,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#766247",
    "soft": "#f6f2eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 74,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-atlantic-crest",
    "name": "Compás Arena",
    "layout": "single",
    "theme": "compass",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 38,
    "accent": "#766247",
    "soft": "#f6f2eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 75,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-modern-two-column-designers",
    "name": "Prisma Arena",
    "layout": "sidebar-right",
    "theme": "prism",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 38,
    "rail": 30,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#766247",
    "soft": "#f6f2eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 76,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-slate-focus",
    "name": "Atelier Arena",
    "layout": "single",
    "theme": "atelier",
    "nameFont": "CV Own Serif",
    "nameSize": 33,
    "margin": 40,
    "accent": "#766247",
    "soft": "#f6f2eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 77,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-confident-grid",
    "name": "Cronología Arena",
    "layout": "single",
    "theme": "chronicle",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 37,
    "accent": "#766247",
    "soft": "#f6f2eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 78,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-simply-blue-minimalistic-professionals",
    "name": "Umbral Arena",
    "layout": "sidebar-right",
    "theme": "threshold",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 39,
    "rail": 31,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#766247",
    "soft": "#f6f2eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 79,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-sandstone-dual",
    "name": "Horizonte Arena",
    "layout": "single",
    "theme": "horizon",
    "nameFont": "CV Own Sans",
    "nameSize": 31,
    "margin": 38,
    "accent": "#766247",
    "soft": "#f6f2eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 80,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-mercury-panel",
    "name": "Módulo Arena",
    "layout": "sidebar-right",
    "theme": "module",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 29,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#766247",
    "soft": "#f6f2eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 81,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-lead-product-designer-ux-ui",
    "name": "Esencia Arena",
    "layout": "single",
    "theme": "essence",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 40,
    "accent": "#766247",
    "soft": "#f6f2eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 82,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-blue-steel-minimalist-professional-classic",
    "name": "Cuaderno Arena",
    "layout": "single",
    "theme": "notebook",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 38,
    "accent": "#766247",
    "soft": "#f6f2eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 83,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-minty-minimalistic-professional",
    "name": "Índice Arena",
    "layout": "single",
    "theme": "index",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "accent": "#766247",
    "soft": "#f6f2eb",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 84,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-royal-blue-two-column",
    "name": "Editorial Oliva",
    "layout": "single",
    "theme": "editorial",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 39,
    "accent": "#596448",
    "soft": "#f1f4ec",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 85,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-charcoal-glow",
    "name": "Archivo Oliva",
    "layout": "sidebar-right",
    "theme": "archive",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 28,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#596448",
    "soft": "#f1f4ec",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 86,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-minimal-qr-code-professionals",
    "name": "Compás Oliva",
    "layout": "single",
    "theme": "compass",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 38,
    "accent": "#596448",
    "soft": "#f1f4ec",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 87,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-azure-line",
    "name": "Prisma Oliva",
    "layout": "sidebar-right",
    "theme": "prism",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 38,
    "rail": 30,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#596448",
    "soft": "#f1f4ec",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 88,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-desert-rock-two-column-professional",
    "name": "Atelier Oliva",
    "layout": "single",
    "theme": "atelier",
    "nameFont": "CV Own Serif",
    "nameSize": 33,
    "margin": 40,
    "accent": "#596448",
    "soft": "#f1f4ec",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 89,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-slate-dawn",
    "name": "Cronología Oliva",
    "layout": "single",
    "theme": "chronicle",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 37,
    "accent": "#596448",
    "soft": "#f1f4ec",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 90,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-calm-blue",
    "name": "Umbral Oliva",
    "layout": "sidebar-right",
    "theme": "threshold",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 39,
    "rail": 31,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#596448",
    "soft": "#f1f4ec",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 91,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-blue-modern-resume-border",
    "name": "Horizonte Oliva",
    "layout": "single",
    "theme": "horizon",
    "nameFont": "CV Own Sans",
    "nameSize": 31,
    "margin": 38,
    "accent": "#596448",
    "soft": "#f1f4ec",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 92,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-aem-developer-resume-template",
    "name": "Módulo Oliva",
    "layout": "sidebar-right",
    "theme": "module",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 29,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#596448",
    "soft": "#f1f4ec",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 93,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-sage-horizon",
    "name": "Esencia Oliva",
    "layout": "single",
    "theme": "essence",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 40,
    "accent": "#596448",
    "soft": "#f1f4ec",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 94,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-elegant-minimalistic-professionals",
    "name": "Cuaderno Oliva",
    "layout": "single",
    "theme": "notebook",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 38,
    "accent": "#596448",
    "soft": "#f1f4ec",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 95,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-steel-two-column-ux-ui-designers",
    "name": "Índice Oliva",
    "layout": "single",
    "theme": "index",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "accent": "#596448",
    "soft": "#f1f4ec",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 96,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-elegant-hunter-green-multi-column",
    "name": "Editorial Granate",
    "layout": "single",
    "theme": "editorial",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 39,
    "accent": "#794452",
    "soft": "#f8eff2",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 97,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-minimalistic-classic-professionals",
    "name": "Archivo Granate",
    "layout": "sidebar-right",
    "theme": "archive",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 28,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#794452",
    "soft": "#f8eff2",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 98,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-minimalist-classic-professional",
    "name": "Compás Granate",
    "layout": "single",
    "theme": "compass",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 38,
    "accent": "#794452",
    "soft": "#f8eff2",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 99,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-amethyst-edge",
    "name": "Prisma Granate",
    "layout": "sidebar-right",
    "theme": "prism",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 38,
    "rail": 30,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#794452",
    "soft": "#f8eff2",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 100,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-warrior-red-multi-column-professional",
    "name": "Atelier Granate",
    "layout": "single",
    "theme": "atelier",
    "nameFont": "CV Own Serif",
    "nameSize": 33,
    "margin": 40,
    "accent": "#794452",
    "soft": "#f8eff2",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 101,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-accentuated-multi-column-red-highlights",
    "name": "Cronología Granate",
    "layout": "single",
    "theme": "chronicle",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 37,
    "accent": "#794452",
    "soft": "#f8eff2",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 102,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-multi-column-elegant-border",
    "name": "Umbral Granate",
    "layout": "sidebar-right",
    "theme": "threshold",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 39,
    "rail": 31,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#794452",
    "soft": "#f8eff2",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 103,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-classic-simple-red-accent",
    "name": "Horizonte Granate",
    "layout": "single",
    "theme": "horizon",
    "nameFont": "CV Own Sans",
    "nameSize": 31,
    "margin": 38,
    "accent": "#794452",
    "soft": "#f8eff2",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 104,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-professional-two-column-monochrome-design",
    "name": "Módulo Granate",
    "layout": "sidebar-right",
    "theme": "module",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 29,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#794452",
    "soft": "#f8eff2",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 105,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-coral-navy",
    "name": "Esencia Granate",
    "layout": "single",
    "theme": "essence",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 40,
    "accent": "#794452",
    "soft": "#f8eff2",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 106,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-classic-elegant-border",
    "name": "Cuaderno Granate",
    "layout": "single",
    "theme": "notebook",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 38,
    "accent": "#794452",
    "soft": "#f8eff2",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 107,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-multi-column-design-marketing-assistants",
    "name": "Índice Granate",
    "layout": "single",
    "theme": "index",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "accent": "#794452",
    "soft": "#f8eff2",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 108,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-minimalistic-grey-modern-simple",
    "name": "Editorial Grafito",
    "layout": "single",
    "theme": "editorial",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 39,
    "accent": "#384047",
    "soft": "#f0f2f3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 109,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-ultra-violet",
    "name": "Archivo Grafito",
    "layout": "sidebar-right",
    "theme": "archive",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 28,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#384047",
    "soft": "#f0f2f3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 110,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-mint-line",
    "name": "Compás Grafito",
    "layout": "single",
    "theme": "compass",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 38,
    "accent": "#384047",
    "soft": "#f0f2f3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 111,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-emerald-mist",
    "name": "Prisma Grafito",
    "layout": "sidebar-right",
    "theme": "prism",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 38,
    "rail": 30,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#384047",
    "soft": "#f0f2f3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 112,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-blue-neon-multi-column-border-accents",
    "name": "Atelier Grafito",
    "layout": "single",
    "theme": "atelier",
    "nameFont": "CV Own Serif",
    "nameSize": 33,
    "margin": 40,
    "accent": "#384047",
    "soft": "#f0f2f3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 113,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-classic-simple-blue-accent",
    "name": "Cronología Grafito",
    "layout": "single",
    "theme": "chronicle",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 37,
    "accent": "#384047",
    "soft": "#f0f2f3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 114,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-two-column-header-professional-layout",
    "name": "Umbral Grafito",
    "layout": "sidebar-right",
    "theme": "threshold",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 39,
    "rail": 31,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#384047",
    "soft": "#f0f2f3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 115,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-multi-column-border-style",
    "name": "Horizonte Grafito",
    "layout": "single",
    "theme": "horizon",
    "nameFont": "CV Own Sans",
    "nameSize": 31,
    "margin": 38,
    "accent": "#384047",
    "soft": "#f0f2f3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 116,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-stylish-two-column-web-developer",
    "name": "Módulo Grafito",
    "layout": "sidebar-right",
    "theme": "module",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 29,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#384047",
    "soft": "#f0f2f3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 117,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-plum-accent",
    "name": "Esencia Grafito",
    "layout": "single",
    "theme": "essence",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 40,
    "accent": "#384047",
    "soft": "#f0f2f3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 118,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-classic-simple-green-accent",
    "name": "Cuaderno Grafito",
    "layout": "single",
    "theme": "notebook",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 38,
    "accent": "#384047",
    "soft": "#f0f2f3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 119,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-aqua-splash-multi-column-marketing",
    "name": "Índice Grafito",
    "layout": "single",
    "theme": "index",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "accent": "#384047",
    "soft": "#f0f2f3",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 120,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-elegant-border-professional-template",
    "name": "Editorial Petróleo",
    "layout": "single",
    "theme": "editorial",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 39,
    "accent": "#285c61",
    "soft": "#edf5f5",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 121,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-classic-green-minimal-border",
    "name": "Archivo Petróleo",
    "layout": "sidebar-right",
    "theme": "archive",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 28,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#285c61",
    "soft": "#edf5f5",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 122,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-minimalistic-gold-design-professionals",
    "name": "Compás Petróleo",
    "layout": "single",
    "theme": "compass",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 38,
    "accent": "#285c61",
    "soft": "#edf5f5",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 123,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-transparent-leaves",
    "name": "Prisma Petróleo",
    "layout": "sidebar-right",
    "theme": "prism",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 38,
    "rail": 30,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#285c61",
    "soft": "#edf5f5",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 124,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-lavender-multi-column-creative-template",
    "name": "Atelier Petróleo",
    "layout": "single",
    "theme": "atelier",
    "nameFont": "CV Own Serif",
    "nameSize": 33,
    "margin": 40,
    "accent": "#285c61",
    "soft": "#edf5f5",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 125,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-classic-border-professional-look",
    "name": "Cronología Petróleo",
    "layout": "single",
    "theme": "chronicle",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 37,
    "accent": "#285c61",
    "soft": "#edf5f5",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 126,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-dark-leaves-multi-column-elegant-design",
    "name": "Umbral Petróleo",
    "layout": "sidebar-right",
    "theme": "threshold",
    "nameFont": "CV Own Sans",
    "nameSize": 30,
    "margin": 39,
    "rail": 31,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#285c61",
    "soft": "#edf5f5",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 127,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-dark-two-column-tech-professionals",
    "name": "Horizonte Petróleo",
    "layout": "single",
    "theme": "horizon",
    "nameFont": "CV Own Sans",
    "nameSize": 31,
    "margin": 38,
    "accent": "#285c61",
    "soft": "#edf5f5",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 128,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-monochrome-two-column-typewriter-style",
    "name": "Módulo Petróleo",
    "layout": "sidebar-right",
    "theme": "module",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "rail": 29,
    "sideSections": [
      "education",
      "skills",
      "languages",
      "websites"
    ],
    "accent": "#285c61",
    "soft": "#edf5f5",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 129,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-minimalist-classic-professional-design",
    "name": "Esencia Petróleo",
    "layout": "single",
    "theme": "essence",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 40,
    "accent": "#285c61",
    "soft": "#edf5f5",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 130,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-sunset-gradient-multi-column-design",
    "name": "Cuaderno Petróleo",
    "layout": "single",
    "theme": "notebook",
    "nameFont": "CV Own Serif",
    "nameSize": 32,
    "margin": 38,
    "accent": "#285c61",
    "soft": "#edf5f5",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 131,
    "collection": "owned-20261003"
  },
  {
    "id": "flow-free-multi-column-border-professionals",
    "name": "Índice Petróleo",
    "layout": "single",
    "theme": "index",
    "nameFont": "CV Own Sans",
    "nameSize": 29,
    "margin": 37,
    "accent": "#285c61",
    "soft": "#edf5f5",
    "supportsPhoto": true,
    "bodySize": 8.7,
    "sectionGap": 17,
    "entryGap": 9,
    "variant": 132,
    "collection": "owned-20261003"
  }
].map(design=>Object.freeze(design)));
